const cssTransform = {
    'matrix':1,
    'matrix3d':1,
    'translate':1,
    'translateX':{'u':'px'},
    'translateY':{'u':'px'},
    'translateZ':{'u':'px'},
    'translate3d':{'u':'px'},
    'scale':1,
    'scaleX':1,
    'scaleY':1,
    'scaleZ':1,
    'scale3d':1,
    'skew':{'u':'deg'},
    'skewX':{'u':'deg'},
    'skewY':{'u':'deg'},
    'rotate':{'u':'deg'},
    'rotateX':{'u':'deg'},
    'rotateY':{'u':'deg'},
    'rotateZ':{'u':'deg'},
    'rotate3d':{'u':'deg'},
    'perspective':{'u':'px'},   
}
export { cssTransform }